'use strict';

// Clipboard history: the last CLIP_MAX things copied - in Cockpit or any other app - kept in
// MEMORY only (never written to disk, gone when Cockpit quits). Anything that looks like a
// secret is removed after CLIP_SECRET_TTL; if it is still on the clipboard then, the clipboard
// itself is cleared too (the way password managers do it), unless that is switched off.
// The clipboard is polled, because no platform tells an app that something else copied.

const CLIP_MAX = 50;
const CLIP_SECRET_TTL = 60 * 1000;
const CLIP_MAX_CHARS = 1024 * 1024; // a copied novel is not history

// Password managers mark what they copy so clipboard tools can leave it alone: macOS
// (nspasteboard.org) and Windows (clipboard history / monitor exclusion formats).
const CONCEALED_FORMAT = /ConcealedType|TransientType|AutoGeneratedType|ExcludeClipboardContentFromMonitorProcessing|CanIncludeInClipboardHistory|CanUploadToCloudClipboard|Clipboard Viewer Ignore/i;

// What the text itself gives away. Order matters: the first match names it.
const SECRET_PATTERNS = [
  [/-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----/, 'private key'],
  [/\bAKIA[0-9A-Z]{16}\b/, 'AWS key'],
  [/\b(gh[pousr]_[A-Za-z0-9]{30,}|github_pat_[A-Za-z0-9_]{20,})\b/, 'GitHub token'],
  [/\bglpat-[A-Za-z0-9_-]{20,}/, 'GitLab token'],
  [/\bxox[abprs]-[A-Za-z0-9-]{10,}/, 'Slack token'],
  [/\bsk-ant-[A-Za-z0-9_-]{20,}/, 'Anthropic key'],
  [/\bsk-(proj-)?[A-Za-z0-9_-]{20,}/, 'API key'],
  [/\bAIza[0-9A-Za-z_-]{35}\b/, 'Google API key'],
  [/\beyJ[A-Za-z0-9_-]{8,}\.eyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}/, 'token (JWT)'],
  // not \b: "_" is a word character, so \bpassword would miss DB_PASSWORD=...
  [/(?:^|[^A-Za-z])(password|passwd|pwd|secret|token|api[_-]?key|client[_-]?secret)\s*[:=]\s*\S{4,}/i, 'password'],
];
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

// A single "word" that looks generated: long enough, no spaces, three kinds of characters,
// and not something that is merely technical (a URL, a path, an address, a hash, an id).
function looksLikePassword(t) {
  if (t.length < 12 || t.length > 128 || /\s/.test(t)) return false;
  if (/:\/\/|^[/~.\\]|\\|@.+\.|^[0-9a-f]+$/i.test(t) || UUID.test(t)) return false;
  const kinds = [/[a-z]/, /[A-Z]/, /[0-9]/, /[^A-Za-z0-9]/].filter((re) => re.test(t)).length;
  return kinds >= 3;
}
function secretKind(text, formats) {
  if ((formats || []).some((f) => CONCEALED_FORMAT.test(String(f)))) return 'from a password manager';
  const t = String(text || '');
  for (const [re, kind] of SECRET_PATTERNS) if (re.test(t)) return kind;
  return looksLikePassword(t.trim()) ? 'looks like a password' : null;
}

class ClipHistory {
  // clipboard: { readText, writeText, clear, availableFormats } (Electron's, or a test double)
  constructor(opts = {}) {
    this.clipboard = opts.clipboard;
    this.onChange = opts.onChange || (() => {});
    this.now = opts.now || (() => Date.now());
    this.clearSecrets = opts.clearSecrets !== false;
    this.entries = []; // newest first: { id, text, at, secret, expires }
    this.last = null; // what the clipboard held at the last look
    this.timer = null;
    this.seq = 0;
  }
  start(ms = 700) {
    if (this.timer) return;
    this.last = this._read(); // what is there already is not "new" - it was copied before
    this.timer = setInterval(() => this.tick(), ms);
  }
  stop() {
    clearInterval(this.timer);
    this.timer = null;
  }
  _read() {
    try {
      return this.clipboard.readText() || '';
    } catch (_) {
      return '';
    }
  }
  _formats() {
    try {
      return this.clipboard.availableFormats ? this.clipboard.availableFormats() : [];
    } catch (_) {
      return [];
    }
  }
  tick() {
    const text = this._read();
    if (text !== this.last) {
      this.last = text;
      if (text && text.length <= CLIP_MAX_CHARS) this._add(text, this._formats());
    }
    this.expire();
  }
  _add(text, formats) {
    const secret = secretKind(text, formats);
    const had = this.entries.findIndex((e) => e.text === text);
    let e;
    if (had !== -1) {
      e = this.entries.splice(had, 1)[0]; // copied again: to the top, same entry
      e.at = this.now();
      if (e.secret) e.expires = this.now() + CLIP_SECRET_TTL;
    } else {
      e = { id: ++this.seq, text, at: this.now(), secret, expires: secret ? this.now() + CLIP_SECRET_TTL : 0 };
    }
    this.entries.unshift(e);
    if (this.entries.length > CLIP_MAX) this.entries.length = CLIP_MAX;
    this.onChange(this.list());
  }
  expire() {
    const now = this.now();
    const gone = this.entries.filter((e) => e.secret && e.expires <= now);
    if (!gone.length) return;
    this.entries = this.entries.filter((e) => !gone.includes(e));
    if (this.clearSecrets && gone.some((e) => e.text === this._read())) {
      try {
        this.clipboard.clear();
      } catch (_) {
        /* nothing to clear with */
      }
      this.last = '';
    }
    this.onChange(this.list());
  }
  list() {
    return this.entries.map((e) => ({ ...e }));
  }
  // Put an entry back on the clipboard. It moves to the top, and is not a "new copy".
  use(id) {
    const e = this.entries.find((x) => x.id === id);
    if (!e) return null;
    try {
      this.clipboard.writeText(e.text);
    } catch (_) {
      return null;
    }
    this.last = e.text;
    this.entries = [e].concat(this.entries.filter((x) => x !== e));
    e.at = this.now();
    this.onChange(this.list());
    return e.text;
  }
  remove(id) {
    const n = this.entries.length;
    this.entries = this.entries.filter((e) => e.id !== id);
    if (this.entries.length !== n) this.onChange(this.list());
  }
  clear() {
    this.entries = [];
    this.onChange(this.list());
  }
}

module.exports = { ClipHistory, secretKind, looksLikePassword, CLIP_MAX, CLIP_SECRET_TTL };
